# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{psm}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["ecin", "daicoden"]
  s.date = %q{2010-04-28}
  s.description = %q{Print Stuff Mail provides an RESTful API for sending snail mail. This library eases interfacing with it.}
  s.email = %q{@copypastel.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".gitignore",
     "README.textile",
     "Rakefile",
     "VERSION",
     "lib/psm.rb",
     "lib/psm/session.rb",
     "psm.gemspec",
     "test/fake_service.rb",
     "test/psm/session_test.rb",
     "test/psm_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/copypastel/print_stuff_mail}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Client library for Print Stuff Mail, the snail mail webservice.}
  s.test_files = [
    "test/fake_service.rb",
     "test/psm/session_test.rb",
     "test/psm_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<addressable>, [">= 2.1.1"])
      s.add_runtime_dependency(%q<json>, [">= 1.2.3"])
      s.add_development_dependency(%q<shoulda>, [">= 2.10.3"])
      s.add_development_dependency(%q<artifice>, [">= 0.5"])
    else
      s.add_dependency(%q<addressable>, [">= 2.1.1"])
      s.add_dependency(%q<json>, [">= 1.2.3"])
      s.add_dependency(%q<shoulda>, [">= 2.10.3"])
      s.add_dependency(%q<artifice>, [">= 0.5"])
    end
  else
    s.add_dependency(%q<addressable>, [">= 2.1.1"])
    s.add_dependency(%q<json>, [">= 1.2.3"])
    s.add_dependency(%q<shoulda>, [">= 2.10.3"])
    s.add_dependency(%q<artifice>, [">= 0.5"])
  end
end

